In [ ]:
'''
Name - Rohan V. patel
Email - rohanpatel1552003@gmail.com


Programming Assignment 8
'''

In [ ]:
'1. Write a Python Program to Add Two Matrices?'

In [13]:
import numpy as np

def add_two_matrices(matrice_a, matrice_b):
    if matrice_a.shape == matrice_b.shape:
        return matrice_a + matrice_b

matrice_a = np.array([[1,2,3],
                      [4,5,6],
                      [7,8,9]])
matrice_b = np.array([[9,8,7],
                      [6,5,4],
                      [3,2,1]])

print(matrice_a.shape)
print(matrice_b.shape)
print(add_two_matrices(matrice_a, matrice_b))

(3, 3)
(3, 3)
[[10 10 10]
 [10 10 10]
 [10 10 10]]


In [ ]:
'2. Write a Python Program to Multiply Two Matrices?'

In [15]:
matrice_a = np.array([[1,2,3],
                      [4,5,6],
                      [7,8,9]])
matrice_b = np.array([[9,8,7],
                      [6,5,4],
                      [3,2,1]])

def matrice_multiplication(matrice_a, matrice_b):
    return np.matmul(matrice_a,matrice_b)

print(matrice_multiplication(matrice_a, matrice_b))

[[ 30  24  18]
 [ 84  69  54]
 [138 114  90]]


In [ ]:
'3. Write a Python Program to Transpose a Matrix?'

In [16]:
def transpose(matrice):
    return matrice.T

matrice = np.array([[1,2,3],
                    [4,5,6],
                    [7,8,9]])
print(transpose(matrice))

[[1 4 7]
 [2 5 8]
 [3 6 9]]


In [ ]:
'4. Write a Python Program to Sort Words in Alphabetic Order?'

In [17]:
word_array = ['Zayn','Harry','Ninja','Drake','Adam','Mighty']

def sort_wordarray(word_array):
    return sorted(word_array)

print(sort_wordarray(word_array))

['Adam', 'Drake', 'Harry', 'Mighty', 'Ninja', 'Zayn']


In [ ]:
'5. Write a Python Program to Remove Punctuation From a String?'

In [49]:
string_1  = '''
          for ($n=0; $n < $lettas; $n++)
{
$subarra = arr_count_char($start, $array);
$size = sizeof($subarra);

if ($size > 0)
{
$rnd = mt_rand(0, $size-1);
$chars = $subarra[$rnd];
$substr = substr($chars, $order-1, 1);
$start = substr($start, 1, strlen($start)-1) . $substr;

// Prints a new line if the char return code is present.
if ($substr == "r")
echo "
";
else
echo $substr;

}
'''

import string 
string_1 = string_1.translate(str.maketrans('', '', string.punctuation))

print(string_1)


          for n0 n  lettas n

subarra  arrcountcharstart array
size  sizeofsubarra

if size  0

rnd  mtrand0 size1
chars  subarrarnd
substr  substrchars order1 1
start  substrstart 1 strlenstart1  substr

 Prints a new line if the char return code is present
if substr  r
echo 

else
echo substr



